@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
content-type: application/json

{
  "name": "Fabricio",
  "email": "fabricio4@gmail.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseURL}}/sessions
content-Type: application/json

{
  "email": "fabricio2@gmail.com",
  "password": "12345678" 
}

###

# @name create_question
POST {{baseURL}}/questions
content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Question do fluxo completo",
  "content": "Será que a question crida pelo fluxo completo funcionou?" 
}

###

# @name fetch_recent_questions
GET {{baseURL}}/questions?page=1
Authorization: Bearer {{authToken}}